name: flutter_application_seniorcare
description: Une application Flutter pour robot assistant

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  uuid: ^4.5.1
  barcode_scan2: ^4.5.1
  flutter_datetime_picker_plus: ^2.0.1

  firebase_core: ^2.27.0 
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.10
  http: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/acceuil.jpg
    - assets/images/login.jpg
    

